:scrollbar:
:data-uri:
:linkattrs:
:toc2:
:labname: Variables
:show_solution: false

==  {labname} Lab

In this lab, you define and use variables in a playbook. You create a playbook that installs the Apache web server and opens the ports for the service to be reachable. The playbook queries the web server to ensure that it is up and running.

.Goals
* Define variables in a playbook and create tasks that include defined variables
* Gather facts from a host and create tasks that use the gathered facts
* Define variables and tasks in separate files and use the files in playbooks

:numbered:


== Connect to Environment

. Set some useful environment variables:
+
[source,sh]
----
[laptop ]$ export GUID=<"GUID from email">
[laptop ]$ export MYKEY=<~/.ssh/your_key.pem>
[laptop ]$ export MYUSER=<username-company.com>
----
+
.Example
[source,sh]
----
[laptop ]$ export GUID=e4gh
[laptop ]$ export MYKEY=~/.ssh/psrivatkey
[laptop ]$ export MYUSER=psrivast-redhat.com
----

. Connect to the `bastion` host with your OPENTLC ID and private key:
+
[source,sh]
----
[laptop ]$ ssh -i ${MYKEY} ${MYUSER}@bastion.${GUID}.example.opentlc.com
----

. Log in as the `devops` user and change to the `~/dev-vars-playbook` directory:
+
[source,sh]
----
[user-company.com@bastion ~]$ sudo -i
[root@bastion ~]# su - devops
[devops@bastion ~]$ cd ~/dev-vars-playbook
[devops@bastion dev-vars-playbook]$
----


== Create Playbook to Set Up Web Services

In this section, you create a playbook to set up web services on the web servers.

. Create the `variable_test.yml` playbook and define the following variables in the `vars` section:

* `web_pkg` defines the name of the package to install for the web server
* `firewall_pkg` defines the name of the firewall package
* `web_service` defines the name of the web service to manage
* `firewall_service` defines the name of the firewall service to manage
* `python_pkg` defines a package to be installed for the `uri` module
* `rule` defines the service to open

. Create the `tasks` block and add a first task, which uses the `yum` module to install the required packages.

. Add two more tasks to start and enable the `httpd` and `firewalld` services.

. Add a task that creates content in `/var/www/html/index.html`.

. Add a task that uses the `firewalld` module to add a rule for the web service.

.Playbook Solution
[source,sh]
----
[devops@bastion ansible_implementation]$ cat << EOF > variable_test.yml
- name: Install Apache and start the service
  hosts: webservers
  become: yes
  vars:
    web_pkg: httpd
    firewall_pkg: firewalld
    web_service: httpd
    firewall_service: firewalld
    python_pkg: python-httplib2
    rule: http
  tasks:
    - name: Install the required packages
      yum:
        name:
          - "{{ web_pkg  }}"
          - "{{ firewall_pkg }}"
          - "{{ python_pkg }}"
        state: latest
    - name: Start and enable the {{ firewall_service }} service
      service:
        name: "{{ firewall_service }}"
        enabled: true
        state: started

    - name: Start and enable the {{ web_service }} service
      service:
        name: "{{ web_service }}"
        enabled: true
        state: started
    - name: Create web content to be served
      copy:
        content: "Example web content"
        dest: /var/www/html/index.html
    - name: Open the port for {{ rule }}
      firewalld:
        service: "{{ rule }}"
        permanent: true
        immediate: true
        state: enabled

EOF
----

[start=6]

. Check the syntax of the `variable_test.yml` playbook:
+
[source,sh]
----
[devops@bastion ansible_implementation]$ ansible-playbook --syntax-check variable_test.yml
----
+
.Sample Output
[source,texinfo]
----
playbook: variable_test.yml
----


== Create Playbook for Smoke Test

In this section, you create a new play that queries the web service to ensure that everything is configured correctly.

. Name your playbook `webserver_smoketest.yml`.
. Configure it to run only on `localhost`.
. Create a task that uses the `uri` module to check a URL.
. In this task, check for a status code of `200` to confirm that the server is running and configured properly.

.Playbook Solution
[source,sh]
----
[devops@bastion ansible_implementation]$ export GUID=`hostname | awk -F"." '{print $2}'`
[devops@bastion ansible_implementation]$ cat << EOF > webserver_smoketest.yml
- name: Verify the Apache service
  hosts: localhost
  tasks:
    - name: Ensure the webserver is reachable
      uri:
        url: http://app1.${GUID}.internal
        status_code: 200
EOF
----


== Run Playbooks

In this section, you run the `variable_test.yml` playbook to set up the web services of `app1` and `app2`. Then you run the `webserver_smoketest.yml` smoke-test playbook to verify that the web services are running on the correct hosts.

. Run the `variable_test.yml` playbook:
+
[source,sh]
----
[devops@bastion ansible_implementation]$ ansible-playbook variable_test.yml
----
+
.Sample Output
[source,texinfo]
----
PLAY [Install Apache and start the service] *******************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************************
ok: [app1.${GUID}.internal]
ok: [app2.${GUID}.internal]

TASK [Install the required packages] **************************************************************************************************************************
changed: [app1.${GUID}.internal]
changed: [app2.${GUID}.internal]

TASK [Start and enable the firewalld service] *****************************************************************************************************************
changed: [app1.${GUID}.internal]
changed: [app2.${GUID}.internal]

TASK [Start and enable the httpd service] *********************************************************************************************************************
changed: [app1.${GUID}.internal]
changed: [app2.${GUID}.internal]

TASK [Create web content to be served] ************************************************************************************************************************
changed: [app1.${GUID}.internal]
changed: [app2.${GUID}.internal]

TASK [Open the port for http] *********************************************************************************************************************************
changed: [app1.${GUID}.internal]
changed: [app2.${GUID}.internal]

PLAY RECAP ****************************************************************************************************************************************************
app1.${GUID}.internal         : ok=6    changed=5    unreachable=0    failed=0
app2.${GUID}.internal         : ok=6    changed=5    unreachable=0    failed=0
----
* Note that Ansible starts by installing the packages, and then starts and enables the services.

. Run the `webserver_smoketest.yml` playbook to make sure that the web server is reachable:
+
[source,sh]
----
[devops@bastion ansible_implementation]$ ansible-playbook webserver_smoketest.yml
----
+
.Sample Output
[source,texinfo]
----
PLAY [Verify the Apache service] ******************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************************
ok: [localhost]

TASK [Ensure the webserver is reachable] **********************************************************************************************************************
ok: [localhost]

PLAY RECAP ****************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
----


== Evaluate Your Progress

. Grade your work:
+
[source,sh]
----
[devops@bastion ansible_implementation]$ cd ~/ansible_implementation_grading
[devops@bastion ansible_implementation_grading]$ export GUID=`hostname | awk -F"." '{print $2}'`
[devops@bastion ansible_implementation_grading]$ ansible-playbook lab-4.1-grade.yml -e GUID=${GUID}
----
+
.Sample Output
[source,texinfo]
----
TASK [Fail if 'Example web content' is not in the page content] ***********************************************************************************************
skipping: [localhost]

TASK [Success if 'Example web content' is in the page content] ************************************************************************************************
ok: [localhost] => {
    "msg": "Success: All requirements completed."
}

PLAY RECAP ****************************************************************************************************************************************************
localhost                  : ok=7    changed=4    unreachable=0    failed=0

----

. Correct any reported failures.

. Rerun the script until you see no failures.


== Clean Up Environment

. Undo the changes made to `webservers`:
+
[source,sh]
----
[devops@bastion ansible_implementation_grading]$ ansible-playbook lab-4.1-cleanup.yml -e GUID=${GUID}
----
