
:scrollbar:
:data-uri:

== Introduction

* Red Hat^(R)^ Ansible^(R)^ Engine Implementation is divided into two parts:

** Part 1: Introduction to Ansible and basic playbook creation (this part)
** Part 2: For intermediate users who want to learn more about Ansible usage

* Part 1 is designed for consultants and systems administrators planning to use Red Hat Ansible Engine for automation, configuration, and management

* Part 1 teaches you how to:
** Automate system administration tasks on managed hosts with Ansible
** Write Ansible Playbooks to standardize task execution
** Manage encryption for Ansible with Ansible Vault

* Labs and assessments test your ability to use Ansible to automate configuration of systems and applications


ifdef::showscript[]

Transcript:

* The Red Hat Ansible Engine Implementation course is divided into two parts:

** Part 1 is an introduction to Ansible and basic playbook creation.
** Part 2 is designed for intermediate users who want to learn more about Ansible usage.

* Part 1 is designed for consultants and systems administrators who are planning to use Ansible for automation, configuration, and management.

* Part 1 teaches you how to automate system administration tasks on managed hosts with Ansible, how to write Ansible Playbooks to standardize task execution, and how to manage encryption for Ansible with Ansible Vault.

* The labs and assessments test your ability to use Ansible to automate the configuration of systems and applications.

endif::showscript[]
