
:scrollbar:
:data-uri:

== Topics

* Roles Overview
* Roles in Playbooks
* Role Creation
* Ansible Galaxy
* `ansible-galaxy`


ifdef::showscript[]

Transcript:

In this module, you learn the following:

* Roles organize Ansible tasks so they can be reused and shared.
* Define role variables in `defaults/main.yml` if they are going to be used as parameters. If not, define them in `vars/main.yml`.
* A role's dependencies can be defined in the `dependencies` section of the role's `meta/main.yml` file.
* Tasks can be applied before and after roles and are included by using `pre_tasks` and `post_tasks` in a playbook.
* Ansible Playbooks define roles in the `roles` section.
* Roles defined in playbooks can override default role variables.
* Ansible Galaxy is a public library of Ansible roles written by Ansible users.
* The `ansible-galaxy` command can search for, display information about, install, list, remove, and initialize roles.
* The `ansible-galaxy init --offline` command creates the directory structure for a new role.


endif::showscript[]



