:scrollbar:
:data-uri:
:linkattrs:
:toc2:
:labname: Ansible Setup and Ad Hoc Command
:show_solution: false


== {labname} Lab

In this lab, you set up and configure the Ansible Controller server for managing remote hosts. You install the required packages on the Controller server, create a user, and set up SSH private keys. Then you test connecting to remote hosts. Finally, you run ad hoc commands to manage the remote hosts.

.Goals
* Install Red Hat Ansible Engine
* Create a user on the remote hosts
* Test connectivity to the remote hosts
* Explore ad hoc commands

:numbered:


[[labexercises]]
== Connect to Environment

. Set some useful environment variables:
+
[source,sh]
----
[laptop ]$ export GUID=<"GUID from email">
[laptop ]$ export MYKEY=<~/.ssh/your_key.pem>
[laptop ]$ export MYUSER=<username-company.com>
----
+
.Example
[source,sh]
----
[laptop ]$ export GUID=e4gh
[laptop ]$ export MYKEY=~/.ssh/psrivatkey
[laptop ]$ export MYUSER=psrivast-redhat.com
----

. Connect to the `bastion` host with your OPENTLC ID and private key:
+
[source,sh]
----
[laptop ]$ ssh -i ${MYKEY} ${MYUSER}@bastion.${GUID}.example.opentlc.com
----

== Configure Ansible Controller

In this section, you set up and configure the `bastion` host as the Ansible Controller server.

You create a `devops` user on the Ansible Controller and generate an SSH key pair for the user. The `devops` user is used to run all of the Ansible CLI commands to manage the remote hosts.

=== Install Ansible

. Install Ansible on the `bastion` host:
+
[source,sh]
----
[user-company.com@bastion ~]$ sudo -i
[root@bastion ~]# yum install ansible
----
+
.Sample Output
[source,texinfo]
----
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
Package ansible-2.6.2-1.el7.noarch already installed and latest version
Nothing to do
----

[NOTE]
The `ansible` package must be installed from a supported repository using `yum`.

=== Create User on Bastion Host and Generate SSH Key Pair

. Create a user named `devops` with the password `r3dh4t1!`:
+
[source,sh]
----
[root@bastion ~]# useradd devops
[root@bastion ~]# echo 'r3dh4t1!' | passwd --stdin devops
----
+
.Sample Output
[source,texinfo]
----
Changing password for user devops.
passwd: all authentication tokens updated successfully.
----

. Generate an SSH key pair for the `devops` user:
+
[source,sh]
----
[root@bastion ~]# su - devops
[devops@bastion ~]$ ssh-keygen -N '' -f ~/.ssh/id_rsa
----
+
.Sample Output
[source,texinfo]
----
Generating public/private rsa key pair.
Created directory '/home/devops/.ssh'.
Your identification has been saved in /home/devops/.ssh/id_rsa.
Your public key has been saved in /home/devops/.ssh/id_rsa.pub.
The key fingerprint is:
SHA256:kmAyJJMCordVF51xd4AmkgzDRYa8rcMUjStBHfL7Dr0 devops@bastion.${GUID}.example.opentlc.com
The key's randomart image is:
+---[RSA 2048]----+
|*...o+=X*+.o..o..|
|=+  .+B+= +.o. . |
|o + +..= . o     |
| . *..+o.        |
|  .  ++.S        |
|      ++         |
|      ..o        |
|       o .       |
|        E        |
+----[SHA256]-----+
----

. Verify that the SSH key was successfully created:
+
[source,sh]
----
[devops@bastion ~]$ ls -l ~/.ssh/
----
+
.Sample Output
[source,texinfo]
----
total 8
-rw-------. 1 devops devops 1675 Aug 16 00:23 id_rsa
-rw-r--r--. 1 devops devops  421 Aug 16 00:23 id_rsa.pub
----


== Set Up Remote Hosts

In this section, you set up the remote hosts. You create the `devops` user on all of the remote hosts and copy its public key to each host.

[NOTE]
The `root` user on the `bastion` host is already set up to connect to the remote host as `ec2-user`. In this lab, you initially use the `root` user to run Ansible ad hoc commands to set up the remote hosts.

=== Explore Environment

. As the `root` user, explore the remote hosts:
+
[source,sh]
----
[root@bastion ~]# ansible all --list-hosts
----
+
.Sample Output
[source,texinfo]
----
  hosts (5):
    frontend1.${GUID}.internal
    support1.${GUID}.internal
    app1.${GUID}.internal
    app2.${GUID}.internal
    appdb1.${GUID}.internal
----

. Test connectivity to the remote hosts:
+
[source,sh]
----
[root@bastion ~]# ansible all -m ping
----
+
.Sample Output
[source,texinfo]
----
app1.${GUID}.internal | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
support1.${GUID}.internal | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
app2.${GUID}.internal | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
frontend1.${GUID}.internal | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
appdb1.${GUID}.internal | SUCCESS => {
    "changed": false,
    "ping": "pong"
}

----

=== Create User and Set Up SSH Keys for Remote Host

In this section, you create the user and set up the SSH keys for the `devops` user on the remote hosts.

. Create the `devops` user on the remote hosts using the Ansible `user` module:
+
[source,sh]
----
[root@bastion ~]# ansible all -m user -a "name=devops"
----
+
.Sample Output
[source,texinfo]
----
appdb1.${GUID}.internal | SUCCESS => {
    "changed": true,
    "comment": "",
    "create_home": true,
    "group": 1001,
    "home": "/home/devops",
    "name": "devops",
    "shell": "/bin/bash",
    "state": "present",
    "system": false,
    "uid": 1001
}
frontend1.${GUID}.internal | SUCCESS => {
    "changed": true,
    "comment": "",
    "create_home": true,
    "group": 1001,
    "home": "/home/devops",
    "name": "devops",
    "shell": "/bin/bash",
    "state": "present",
    "system": false,
    "uid": 1001
}

output omitted....
----

. Display the SSH public key for the `devops` user:
+
[source,sh]
----
[root@bastion ~]# cat /home/devops/.ssh/id_rsa.pub
----
+
.Sample Output
[source,texinfo]
----
ssh-rsa AAAABLzz3......lxV1sZld0sGVP devops@bastion.${GUID}.example.opentlc.com
----

. Add the SSH key to the authorized keys for the `devops` user, making sure to replace the value of the SSH public key with the one that you just displayed:
+
[source,sh]
----
[root@bastion ~]# ansible all -m authorized_key -a "user=devops state=present key='ssh-rsa AAAAB......3lxV1sZld0sGVP devops@bastion.${GUID}.example.opentlc.com'"
----
* The contents of `/home/devops/.ssh/id_rsa.pub` is used as the value of the parameter `key` for the `authorized_key` Ansible module.
+
.Sample Output
[source,texinfo]
----
app1.${GUID}.internal | SUCCESS => {
    "changed": true,
    "comment": null,
    "exclusive": false,
    "key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDfPKFdlmfxH8+xbVtJdSy1Jhc53lZCyKnS6NVm2GzobK3T4ZJKm8VBRV2WSOieOoy0cChygqEI7thpIGSJ69n/hwEC8lRbTpPNJQs7NNf6SrgmhWkep82CQtO8ElkzssEtwNbAXsC7Bzt1OKtdHPGpMJdB7KwGFD8NarrF2nbRWTWjoSoUhm6WNZ3kjPbXZH5STSjwrNnq0FWj9PpHs3d6dqjBj1X+pcAuao4/CJ1s++cVcK3s5aHjNGAnzZffILHx8jWPVsPuzECm7pu3R3H6L07B2R/k9x+eezBMcW/Pyu6M4aGNX4xQPnv2KMtLQTblEcbLzz3lxV1sZld0sGVP devops@bastion.${GUID}.example.opentlc.com",
    "key_options": null,
    "keyfile": "/home/devops/.ssh/authorized_keys",
    "manage_dir": true,
    "path": null,
    "state": "present",
    "unique": false,
    "user": "devops",
    "validate_certs": true
}
Output Omited....
----

. Configure `sudo` on the remote host for privileged escalation for the `devops` user:
+
[source,sh]
----
[root@bastion ~]# ansible all -m lineinfile -a "dest=/etc/sudoers state=present line='devops ALL=(ALL) NOPASSWD: ALL'"
----
+
.Sample Output
[source,texinfo]
----
appdb1.${GUID}.internal | SUCCESS => {
    "backup": "",
    "changed": true,
    "msg": "line added"
}
app1.${GUID}.internal | SUCCESS => {
    "backup": "",
    "changed": true,
    "msg": "line added"
}
Output Omitted....
----

. Verify the connection to the remote hosts from `bastion` as the `devops` user, starting with the `app1` server:
+
[source,sh]
----
[root@bastion ~]# su - devops
[devops@bastion ~]$ export GUID=`hostname | awk -F"." '{print $2}'`
[devops@bastion ~]$ ssh app1.${GUID}.internal
----
+
.Sample Output
[source,texinfo]
----
The authenticity of host 'app1.${GUID}.internal (<no hostip for proxy command>)' can't be established.
ECDSA key fingerprint is SHA256:VoJ8NXtSBgbB/YK59iA7yzop56MuGSavYg/0prLGEu4.
ECDSA key fingerprint is MD5:ee:d9:66:8d:8f:f7:19:bf:9d:a5:79:c2:a9:dc:44:24.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'app1.${GUID}.internal' (ECDSA) to the list of known hosts.
Last login: Thu Aug 16 00:54:17 2018
----

. Become the `root` user on the `app1` server:
+
[source,sh]
----
[devops@app1 ~]$ sudo -i
----
+
.Sample Output
[source,texinfo]
----
[root@app1 ~]#
----

. Repeat the previous two steps for all of the other remote hosts.


== Explore Ad Hoc Commands

After you have successfully configured the Ansible Controller and remote hosts, you can run Ansible ad hoc commands and playbooks as the `devops` user from `bastion` without being prompted for the password.

In this section, you explore ad hoc commands to manage remote hosts.

You configure `ansible.cfg` and the static inventory needed to complete this lab. You use `-u` to specify the `devops` user and `--private-key` to specify the private key.

. Verify connectivity to the remote hosts:
+
[source,sh]
----
[devops@bastion ~]$ ansible frontends -m ping
----
+
.Sample Output
[source,texinfo]
----
frontend1.${GUID}.internal | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Warning: Permanently added 'frontend1.${GUID}.example.opentlc.com' (ECDSA) to the list of known hosts.\r\nno such identity: /home/devops/.ssh/${GUID}key.pem: No such file or directory\r\nPermission denied (publickey,gssapi-keyex,gssapi-with-mic).\r\n",
    "unreachable": true
}

----
* The command is expected to fail because it is using the default `ansible.cfg` and the SSH keys defined in the default `/etc/ansible/hosts` static inventory.

. Create a directory called `ansible_implementation` as your working directory for all future labs and an `ansible.cfg` file with a `[defaults]` section for specifying user-specific settings:
+
[source,sh]
----
[devops@bastion ~]$ mkdir ansible_implementation
[devops@bastion ~]$ cd ansible_implementation/
[devops@bastion ansible_implementation]$ cat << EOF > ansible.cfg
[defaults]
inventory = /home/devops/ansible_implementation/hosts
host_key_checking = False
EOF
----

. Verify the contents of the `ansible.cfg` file:
+
[source,sh]
----
[devops@bastion ansible_implementation]$ cat ansible.cfg
----
+
.Sample Output
[source,texinfo]
----
[defaults]
inventory = /home/devops/ansible_implementation/hosts
host_key_checking = False
----

. Create `/home/devops/ansible_implementation/hosts` as the static inventory, which contains the hostnames of all of the remote hosts:
+
[source,sh]
----
[devops@bastion ansible_implementation]$ export GUID=`hostname | awk -F"." '{print $2}'`
[devops@bastion ansible_implementation]$ cat << EOF > /home/devops/ansible_implementation/hosts
frontend1.${GUID}.internal
appdb1.${GUID}.internal
app1.${GUID}.internal
support1.${GUID}.internal
app2.${GUID}.internal
EOF
----

. Test connectivity again--and this time, expect it to work:
+
[source,sh]
----
[devops@bastion ansible_implementation]$ ansible frontend1.${GUID}.internal -m ping -u devops --private-key=~/.ssh/id_rsa
----
+
.Sample Output
[source,texinfo]
----
frontend1.${GUID}.internal | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
----

. Test connectivity to all of the hosts:
+
[source,sh]
----
[devops@bastion ansible_implementation]$ ansible all -m ping -u devops --private-key=~/.ssh/id_rsa
----
+
.Sample Output
[source,texinfo]
----
app1.${GUID}.internal | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
support1.${GUID}.internal | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
Output Omitted....
----

. Execute an ad hoc command on `localhost` to identify the user account used by Ansible to perform operations on managed hosts:
+
[source,sh]
----
[devops@bastion ansible_implementation]$ ansible localhost -m command -a 'id'
----
+
.Sample Output
[source,texinfo]
----
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

localhost | SUCCESS | rc=0 >>
uid=1001(devops) gid=1001(devops) groups=1001(devops) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023'
----
* Expect to see that the ad hoc command is performed on the managed host as the `devops` user.

. Execute an ad hoc command to display the contents of the `/etc/motd` file on `app1.${GUID}.internal` as the `devops` user:
+
[source,sh]
----
[devops@bastion ansible_implementation]$ ansible app1.${GUID}.internal -m command -a 'cat /etc/motd' -u devops --private-key=~/.ssh/id_rsa
----
+
.Sample Output
[source,texinfo]
----
app1.${GUID}.internal | SUCCESS | rc=0 >>
----
* Note that the `/etc/motd` file is currently empty.

. Execute an ad hoc command using the `copy` module and the `devops` account to change the contents of the `/etc/motd` file to include the message "Managed by Ansible" on all of the remote hosts:
+
[source,sh]
----
[devops@bastion ansible_implementation]$ ansible all -m copy -a 'content="Managed by Ansible\n" dest=/etc/motd' -u devops --private-key=~/.ssh/id_rsa
----
* Expect the ad hoc command to fail due to insufficient permissions:
+
.Sample Output
[source,texinfo]
----
app1.${GUID}.internal | FAILED! => {
    "changed": false,
    "checksum": "4458b979ede3c332f8f2128385df4ba305e58c27",
    "msg": "Destination /etc not writable"
}
Output Omitted...
----

. Create the `/etc/motd` file on all of the hosts, but this time, escalate the `root` user's privileges using `-b` or `--become`:
+
[source,sh]
----
[devops@bastion ansible_implementation]$ ansible all -m copy -a 'content="Managed by Ansible\n" dest=/etc/motd' -u devops --private-key=~/.ssh/id_rsa --become
----
+
.Sample Output
[source,texinfo]
----
app1.${GUID}.internal | SUCCESS => {
    "changed": true,
    "checksum": "4458b979ede3c332f8f2128385df4ba305e58c27",
    "dest": "/etc/motd",
    "gid": 0,
    "group": "root",
    "md5sum": "65a4290ee5559756ad04e558b0e0c4e3",
    "mode": "0644",
    "owner": "root",
    "secontext": "system_u:object_r:etc_t:s0",
    "size": 19,
    "src": "/home/devops/.ansible/tmp/ansible-tmp-1534387341.14-178337610750037/source",
    "state": "file",
    "uid": 0
}
Output Omitted...
----

. Execute an ad hoc command to verify the changes to `/etc/motd` on all of the remote hosts:
+
[source,sh]
----
[devops@bastion ansible_implementation]$ ansible all -m command -a 'cat /etc/motd' -u devops --private-key=~/.ssh/id_rsa --become
----
+
.Sample Output
[source,texinfo]
----
app1.${GUID}.internal | SUCCESS | rc=0 >>
Managed by Ansible

support1.${GUID}.internal | SUCCESS | rc=0 >>
Managed by Ansible

frontend1.${GUID}.internal | SUCCESS | rc=0 >>
Managed by Ansible

appdb1.${GUID}.internal | SUCCESS | rc=0 >>
Managed by Ansible

app2.${GUID}.internal | SUCCESS | rc=0 >>
Managed by Ansible
----


== Evaluate Your Progress

. Change to your home directory (`/home/devops`) before cloning the grading repository:
+
[source,sh]
----
[devops@bastion ansible_implementation]$ cd ~
----

. Grade your work:
+
[source,sh]
----
[devops@bastion ~]$ git clone https://github.com/prakhar1985/ansible_implementation_grading.git
[devops@bastion ~]$ cd ansible_implementation_grading/
[devops@bastion ansible_implementation_grading]$ export GUID=`hostname | awk -F"." '{print $2}'`
[devops@bastion ansible_implementation_grading]$ ansible-playbook lab-2-grade.yml -e GUID=${GUID}
----

. Correct any reported failures.

. Rerun the script until you see no failures.
